import type { Metadata } from "next";
import "./global.css";



export const metadata: Metadata = {
  title: "RHJ",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  },
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
