on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 단계(step)들이 이어집니다.
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 필요에 따라 버전 조정
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/hobbang/Project/profile
            git pull origin main
            npm install
            npm run build
            pm2 restart profile  # PM2를 사용하는 경우
